const activities = [
  {
    id: "stretch",
    icon: "🙆",
    title: "Quick Stretch",
    instruction: "Stand up, reach your arms overhead, and slowly roll your neck left and right. Shake out your hands and shoulders.",
    duration: 30,
    completion: "Muscles loosened! Blood is flowing again.",
  },
  {
    id: "hydrate",
    icon: "💧",
    title: "Hydration Check",
    instruction: "Go grab a glass of water right now. Take 5 slow, deliberate sips. Feel the coolness and come back refreshed.",
    duration: 30,
    completion: "Hydrated and ready. Your brain thanks you.",
  },
  {
    id: "look-away",
    icon: "👁️",
    title: "Eye Rest (20-20-20)",
    instruction: "Look at something at least 20 feet away from you for 20 seconds. Blink slowly. Then gently close your eyes for 10 seconds.",
    duration: 40,
    completion: "Eye strain relieved. Screen fatigue reset.",
  },
  {
    id: "gratitude",
    icon: "✨",
    title: "One Good Thing",
    instruction: "Think of one thing you're genuinely grateful for today. Hold that thought for 20 seconds. Let yourself feel it.",
    duration: 30,
    completion: "Perspective shifted. You're doing great.",
  },
  {
    id: "breathe",
    icon: "🌬️",
    title: "Box Breathing",
    instruction: "Breathe in for 4 counts, hold for 4, breathe out for 4, hold for 4. Repeat 3 times.",
    duration: 60,
    completion: "Nervous system calmed. Focus restored.",
  },
  {
    id: "posture",
    icon: "🪑",
    title: "Posture Reset",
    instruction: "Sit up straight. Roll your shoulders back and down. Unclench your jaw. Take one deep breath in this new position.",
    duration: 20,
    completion: "Posture corrected. You'll thank yourself later.",
  },
];
