const facts = [
  "Your brain generates about 70,000 thoughts per day.",
  "The brain uses roughly 20% of all the body's energy.",
  "Octopuses have three hearts and blue blood.",
  "Honey never spoils — archaeologists found 3,000-year-old edible honey in Egyptian tombs.",
  "A group of flamingos is called a 'flamboyance.'",
  "The shortest war in history lasted only 38–45 minutes.",
  "Bananas are technically berries, but strawberries are not.",
  "The word 'nerd' was first coined by Dr. Seuss in 1950.",
  "Crows can recognize and remember human faces.",
  "Your nose can detect over 1 trillion different scents.",
  "A day on Venus is longer than a year on Venus.",
  "Sharks are older than trees — they've existed for over 450 million years.",
  "The human body contains enough carbon to make about 900 pencils.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "The Eiffel Tower grows about 15 cm taller in summer due to heat expansion.",
  "There are more stars in the universe than grains of sand on Earth.",
  "Butterflies taste with their feet.",
  "A bolt of lightning is five times hotter than the surface of the Sun.",
  "The average person walks about 100,000 miles in a lifetime.",
  "Sleeping less than 6 hours a night impairs cognitive performance as much as being drunk.",
];
